channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=25.0.1
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.24.4
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.2.2
  - scipy==1.15.2
name: mlflow-env
