channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=25.1.1
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.24.4
  - psutil==7.0.0
  - scikit-learn==1.2.2
  - scipy==1.13.1
name: mlflow-env
